In [6]:
import pandas as pd
import numpy as np
import io

In [7]:
# 1. Read the raw text from the CSV
with open('data.csv', 'r') as file:
    raw_text = file.read()

# 2. Strip out all the problematic double quotes
clean_text = raw_text.replace('"', '')

# 3. Load it into a pandas DataFrame
df = pd.read_csv(io.StringIO(clean_text))

In [8]:
df.head()

,timestamp,open,high,low,close,volume_btc,volume_usd
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67

In [9]:
df.columns

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume_btc',
       'volume_usd'],
      dtype='object')

In [10]:
window = 3
df['rolling_mean'] = df['close'].rolling(window=window).mean()

In [11]:
df.head()

,timestamp,open,high,low,close,volume_btc,volume_usd,rolling_mean
0,2024-01-01 00:00:00,44910.83,45085.78,44910.83,45024.68,3.640837,163927.55,NaN
1,2024-01-01 00:01:00,44977.19,45045.33,44977.19,45017.83,33.752474,1519463.07,NaN
2,2024-01-01 00:02:00,44991.38,45103.85,44965.65,45050.03,5.488855,247273.08,45030.846667
3,2024-01-01 00:03:00,45056.78,45135.78,45056.78,45125.82,8.464271,381957.14,45064.560000
4,2024-01-01 00:04:00,45172.02,45222.19,44979.72,45114.17,21.673405,977777.67,45096.673333

In [12]:
rolling_mean_avg = df['rolling_mean'].fillna(0.0)
rolling_mean_avg

0           0.000000
1           0.000000
2       45030.846667
3       45064.560000
4       45096.673333
            ...
9995    44091.823333
9996    44099.886667
9997    44077.173333
9998    44041.373333
9999    44048.433333
Name: rolling_mean, Length: 10000, dtype: float64

In [31]:
signal = np.where(
    df['close'] > rolling_mean_avg, 1, 0
)

In [32]:
signal.mean()

np.float64(0.501)